version: '3.8'

services:
  manim-mcp:
    image: manim-mcp-server:latest
    ports:
      - "8001:8001"
    volumes:
      # Mount output directory to persist rendered videos
      - ./output:/app/output
      # Mount uploads directory
      - ./uploads:/app/uploads
    environment:
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
